#!/bin/sh

windowtitle(){
	title=$(xdotool getactivewindow getwindowname 2>/dev/null)
	if [ -z "$title" ]
		then
			echo "Desktop"

	else
		echo "$title"
	fi
}

while true; do
	echo "%{l}%{B#FB9FB1} $(windowtitle) %{B}%{r}"
	sleep 0.3s;
done |

./lemonbar -g 1920x30 -F#FAFAFA -B#00333333 2>/dev/null | bash
