#!/bin/sh
Song() {
	if [ $(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.soundnode /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'                                         \
  | grep -Ev "^method"                           `# Ignore the first line.`   \
  | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' `# Filter interesting fiels.`\
  | sed -E '2~2 a|'                              `# Mark odd fields.`         \
  | sed -E 's/^"//'                              `# Strip leading...`         \
  | sed -E 's/"$//') = "Playing" ]; then
		dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.soundnode /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'                                         \
		| grep -Ev "^method"                           `# Ignore the first line.`   \
		| grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' `# Filter interesting fiels.`\
		| sed -E '2~2 a|'                              `# Mark odd fields.`         \
		| tr -d '\n'                                   `# Remove all newlines.`     \
		| sed -E 's/\|/\n/g'                           `# Restore newlines.`        \
		| sed -E 's/(xesam:)|(mpris:)//'               `# Remove ns prefixes.`      \
		| sed -E 's/^"//'                              `# Strip leading...`         \
		| sed -E 's/"$//'                              `# ...and trailing quotes.`  \
		| sed -E 's/"+/|/'                             `# Regard "" as seperator.`  \
		| sed -E 's/ +/ /g'                            `# Merge consecutive spaces.` \
		| egrep "title" | cut -d '|' -f2 \
		| sed -E ':a;N;$!ba;s/\n/ - /g'
	else
		echo "Paused"
	fi
}

while true; do
	echo " %{r}%{B#6FC2EF} $(Song) %{B}%{r}"
	sleep 0.1s;
done |

~/.config/.bar/lemonbar -g 1920x30 -F#FAFAFA -B#00333333 2>/dev/null | bash
